# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7254c51fbb53e328dd72836db569f1f87db604f64f4af78029c3fb210529515a338ac2fb23ca65ab147850b38511bcaa8d9700c8525a1c650a4cf5261814fc4c

test:
  secret_key_base: 91946b900a9056714b9d91c88255c14288e310fe3e169e26873fd4151e64147b8743b0d001e5b44420c800d60a9424ad5964dc0adade5bd7711751810ca380ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
